### ISSUE TITLE
Error in importing freenect package

### ISSUE THREAD

**Issue by james-tom-ai** [sieuwe1/Advanced-Real-Time-Self-Driving#1]
Hi,

I couldn't find the package to communicate with Kinect. Can you specify which package you used (the package from with FREENECT is imported) ? 

also is there a pip install version of that with which could be installed directly from windows cmd terminal?

I am using windows PC and setting up a separate environment in anaconda to do this project.

@sieuwe1 Could you please help me resolve this issue?

**Comment by sieuwe1** [comment]
Hi

I just cloned this repo https://github.com/OpenKinect/libfreenect and then build it from source using the build example in the readme. Then verified the install by running one of the Python examples.

**Comment by james-tom-ai** [comment]
Thankyou very much !@sieuwe1 

I tried building from the repo you mentioned and it worked in ubuntu.
Is there a way to build it in windows based machine? I tried using the method from the same repo but it failed for windows.
